"""ESPRESSO scraper — Royal Caribbean & Celebrity Cruises.

Ported from adapter_espresso.js. Uses Playwright to automate the
ESPRESSO portal flow: login check → search → read category →
load categories table → click radio → execute API calls → parse results.

SAFETY BOUNDARY — DO NOT CHANGE:
This scraper must never interact with #repriceModalAcceptBtn1 /
#repriceModalAcceptBtn2 ("Continue with New Rate") or any other control
that commits a new rate to a live booking. That is confirmed (directly
from the portal's own markup) to be the actual save action. Everything
this file does — including the direct showRepriceModalCheck fetch call
in _execute_api_calls — stops at reading the Rate Comparison data
(old/new invoice, OBC, offers). The equivalent of clicking "Continue"
on the categories page (#submitToContinue, _eventId=saveCategories) is
simulated read-only via the allocate fetch call; the equivalent of
clicking "Continue with New Rate" must never be added here. That step
is reserved for a human, in the real portal, permanently.
"""

from __future__ import annotations

import asyncio
import json
import re
import time

from config.settings import settings
from core.calculator import (
    calculate_espresso,
    find_upgrade_candidates,
    is_paid_in_full,
    make_no_price_change_result,
    make_paid_in_full_result,
    make_skip_reprice_result,
    make_upgrade_available_result,
    make_wlt_result,
)
from core.models import BookingResult, BookingStatus, CruiseLine
from utils.logging import get_logger
from utils.retry import retry_async

from .base import BaseScraper

logger = get_logger(__name__)

# Matches an unrendered Mustache/Angular-style template placeholder,
# e.g. "{{sb.reservation.category.priceCategory}}", so we can tell it
# apart from a real category code like "ZI".
_TEMPLATE_PLACEHOLDER_RE = re.compile(r"^\{\{.*\}\}$")


def _is_template_placeholder(value: str) -> bool:
    return bool(_TEMPLATE_PLACEHOLDER_RE.match(value.strip()))


_DUAL_RATE_COLUMN_NOTE = (
    " [NOTE: this booking has a second rate-program column (c3) on the "
    "categories table that was captured but NOT evaluated — verify by hand "
    "whether it shows a lower price than the one used here]"
)


def _append_dual_rate_note(note: str, market_data: dict | None) -> str:
    """Extracted as a pure function (2026-08-13, Phase 0 correctness audit)
    so the dual-rate-column visibility fix is directly unit-testable.
    See check_booking's own comment for why this only appends a note
    rather than comparing c2/c3 prices — no live evidence exists for what
    c3 actually means, so guessing at it is deliberately avoided."""
    if market_data and market_data.get("dualRateColumns"):
        return note + _DUAL_RATE_COLUMN_NOTE
    return note


class EspressoScraper(BaseScraper):
    """Scraper for ESPRESSO (Royal Caribbean / Celebrity) portal."""

    cruise_line = CruiseLine.ESPRESSO

    async def _check_login(self) -> bool:
        """Verify user is logged in, based on whatever page we're currently on."""
        url = self.page.url
        if "login" in url or "signin" in url:
            logger.warning("login.required", msg="Not logged in — please log into ESPRESSO first")
            return False
        return "cruisingpower.com" in url

    # ESPRESSO's reservation search box was rebuilt on Mantine at some
    # point — the old plain `#reservationid` input/`#searchReservationBtn`
    # button no longer exist on the redesigned page (confirmed against a
    # live capture of the current portal). Mantine assigns a fresh
    # autogenerated id per render, so the stable hook is the `data-qa`
    # attribute, not an id. Both selectors are tried together (old first)
    # so this keeps working if either version of the page is ever served.
    _SEARCH_INPUT_SELECTOR = (
        '#reservationid, [data-qa="secure.espresso.input.reservation.search"]'
    )
    _SEARCH_BUTTON_SELECTOR = (
        '#searchReservationBtn, [aria-label="Search by Reservation ID, Name or Date"]'
    )

    async def _search_booking(self, booking_id: str) -> None:
        """Submit a booking ID in the search form."""
        # Login can still be mid-way through ESPRESSO's OAuth SSO redirect
        # chain (login -> auth.cruisingpower.com -> oauth callback ->
        # reservations.do) when we get here — that can take longer than
        # the generic 30s action timeout, so wait for the search box
        # itself with a dedicated, longer timeout before touching it.
        try:
            await self.wait_for(self._SEARCH_INPUT_SELECTOR, timeout=settings.scraper_login_timeout_ms)
        except Exception:
            # CONFIRMED REAL PATTERN, 2026-08-17 run: 9 consecutive bookings
            # (15:39-16:12) all failed here with a generic Playwright
            # timeout, one of them (3000032) showing in its own error log
            # that the page navigated through an OAuth endSession call and
            # landed on /login WHILE this wait was in progress — the
            # session died in the gap between _check_login() passing (just
            # before this call) and the search box actually appearing, so
            # the existing "Not logged in" checks around this call never
            # caught it. Re-checking login here doesn't fix the retry — it
            # already retries via retry_async — but it turns a cryptic raw
            # timeout into a clear, correctly-labeled error so it's obvious
            # from the note/error field alone that this was a session
            # logout, not a slow page or a real portal error.
            if not await self._check_login():
                raise RuntimeError(
                    "Session logged out while searching — please log into ESPRESSO again"
                )
            raise
        await self.page.fill(self._SEARCH_INPUT_SELECTOR, "")
        await self.page.fill(self._SEARCH_INPUT_SELECTOR, booking_id)
        await self.page.click(self._SEARCH_BUTTON_SELECTOR)
        # Some bookings' search-result pages render the sidebar noticeably
        # slower (observed recurring timeouts on real bookings at 15s while
        # every other booking clears well under it) — 25s gives those the
        # room to load without meaningfully slowing down the normal case.
        await self.wait_for("#sideBar, [id*='sideBar']", timeout=25000)

    async def _read_category(self) -> str | None:
        """Read the current price category from the booking page.

        Right after the search results load, this value can briefly be
        the literal unrendered template string (e.g.
        "{{sb.reservation.category.priceCategory}}") before the page's
        client-side templating finishes. Poll until we get a real value
        or the timeout elapses, rather than returning the placeholder.
        """
        read_js = """
            (() => {
                const h = document.getElementById('currentPriceCat');
                if (h?.value?.trim()) return h.value.trim();
                const s = document.querySelector('[class*="priceCategory"] [class*="value"]')
                       || document.querySelector('.priceCategory .value');
                return s?.textContent?.trim() || null;
            })()
        """
        deadline = time.monotonic() + settings.scraper_category_poll_timeout_ms / 1000
        cat: str | None = None
        while True:
            cat = await self.page.evaluate(read_js)
            if cat and not _is_template_placeholder(cat):
                return cat
            if time.monotonic() >= deadline:
                if cat:
                    logger.warning("espresso.category_still_placeholder", value=cat)
                return None
            await asyncio.sleep(0.2)

    async def _check_wlt(self, category: str) -> bool:
        """Check if the current category is waitlisted in the categories table."""
        result = await self.page.evaluate(f"""
            (() => {{
                const tbody = document.querySelector('#catAvailCategoryList tbody')
                           || document.querySelector('[id*="catAvail"] tbody');
                if (!tbody) return false;
                for (const row of tbody.querySelectorAll('tr')) {{
                    const icon = row.querySelector('td.c1 div.categoryIcon span, .categoryIcon span');
                    if (icon && icon.textContent.trim() === '{category}') {{
                        const st = row.querySelector('td.c2.rooms .svCabin .status, .svCabin .status')?.textContent?.trim();
                        return st === 'WLT';
                    }}
                }}
                return false;
            }})()
        """)
        return bool(result)

    async def _check_paid_status(self) -> dict | None:
        """Fallback paid-status check, kept for defense in depth inside the
        short-response branch. Its own selectors were guessed and never
        verified — checked against 590 real captured bookings, the "paid in
        full" text fallback below matched zero of them. _read_payment_status
        (below), run as an early gate right after search, is the reliable
        path now; this only matters if that early gate is ever skipped."""
        result = await self.page.evaluate("""
            (() => {
                const totalEl = document.querySelector('[class*="totalPrice"] .amount, .total-price .amount, #totalPrice');
                const paidEl = document.querySelector('[class*="paymentsReceived"] .amount, .payments-received .amount, #paymentsReceived');
                if (totalEl && paidEl) {
                    const total = parseFloat(totalEl.textContent.replace(/[^0-9.]/g, '')) || 0;
                    const paid = parseFloat(paidEl.textContent.replace(/[^0-9.]/g, '')) || 0;
                    if (total > 0 && paid >= total) return { isPaid: true, totalPrice: total };
                }
                const bodyText = document.body?.innerText || '';
                if (/paid\\s+in\\s+full/i.test(bodyText)) return { isPaid: true, totalPrice: 0 };
                return { isPaid: false };
            })()
        """)
        return result

    _PAYMENT_FIELD_PATTERNS = {
        "total_price": re.compile(r"Total Price \(USD\):\s*(-?[\d,]+\.?\d*)", re.IGNORECASE),
        "deposit": re.compile(r"Deposit \(USD\):\s*(-?[\d,]+\.?\d*)", re.IGNORECASE),
        "payments_received": re.compile(r"Payments Received \(USD\):\s*(-?[\d,]+\.?\d*)", re.IGNORECASE),
        "final_payment_due": re.compile(r"Final Payment Due \(USD\):\s*(-?[\d,]+\.?\d*)", re.IGNORECASE),
    }

    # ADDED 2026-08-13 (Phase 0 correctness audit): the amount patterns
    # above are deliberately UNCHANGED (still require the literal "(USD)"
    # label) — this only adds detection of whatever currency code the page
    # actually shows, without touching how any amount is parsed. Confirmed
    # real risk this closes: if ESPRESSO/Celebrity ever renders "(CAD)" (or
    # any non-USD code) instead, the amount patterns above already
    # correctly fail to match (returning None, not a wrong USD-shaped
    # number) — but nothing previously recorded WHY, or distinguished that
    # from "this field just wasn't on the page." This makes that distinction
    # visible via the `currency` key below, generalized to any 3-letter
    # code rather than assuming USD.
    _CURRENCY_LABEL_RE = re.compile(
        r"(?:Total Price|Deposit|Payments Received|Final Payment Due)\s*\(([A-Z]{3})\)",
        re.IGNORECASE,
    )

    async def _read_payment_status(self) -> dict:
        """Reads Total Price / Deposit / Payments Received / Final Payment
        Due directly from the Reservation Summary page's plain body text.
        Confirmed against 590 real bookings: whenever Total Price is
        present, Final Payment Due is too — and it's already reconciled
        for taxes/credits/adjustments, so it's used directly by
        is_paid_in_full() rather than re-derived from Total minus Received.

        Also returns "currency": the 3-letter code actually shown next to
        these labels (e.g. "USD"), or None if no such label was found at
        all. Never assume "USD" when this is None — see BookingResult.currency."""
        body_text = await self.page.inner_text("body")
        values: dict[str, float | None] = {}
        for key, pattern in self._PAYMENT_FIELD_PATTERNS.items():
            m = pattern.search(body_text)
            values[key] = float(m.group(1).replace(",", "")) if m else None
        currency_match = self._CURRENCY_LABEL_RE.search(body_text)
        values["currency"] = currency_match.group(1).upper() if currency_match else None
        return values

    async def _click_categories(self) -> None:
        """Click the Categories link to load the category table."""
        await self.page.evaluate("""
            (() => {
                const a = Array.from(document.querySelectorAll('a')).find(
                    el => el.textContent.trim() === 'Categories'
                ) || document.querySelector('#sideBar a[href*="catAvail"]')
                  || document.querySelector('a[href*="categor"]');
                if (a) a.click();
            })()
        """)
        await self.wait_for("#catAvailCategoryList, [id*='catAvail']", timeout=12000)

    async def _capture_category_table(self, current_category: str | None = None) -> dict:
        """Capture the loaded ESPRESSO category table state without mutating the page.

        Some bookings (confirmed both on group bookings and at least one
        individual booking, 2026-08-09) render TWO side-by-side rate-program
        columns per row via a `columnSelection` radio pair — e.g. "Group
        Allocation - Best Rate" vs "Group Prevailing - Best Rate", or
        "Individual - Best Rate" vs "Individual - Best Value". Only the
        left (`c2`, always pre-checked) column has ever been read by this
        scraper or fed into any decision logic — the right (`c3`) column's
        price has never been captured at all. Neon's observation, from
        working the real portal: the right-hand column sometimes shows a
        genuinely lower price than the left. Both columns' cells already
        exist in the same page load (no extra click/request needed), so
        this now records both, purely as additional captured data — it
        does NOT feed either column into any pricing decision yet. That is
        deliberately deferred until there's a real evidence base of when/how
        often the two columns actually diverge (same lesson as the
        free-upgrade-detection incident: verify before deciding, never
        guess which column is "right")."""
        result = await self.page.evaluate(f"""
            (() => {{
                const tbody = document.querySelector('#catAvailCategoryList tbody')
                           || document.querySelector('[id*="catAvail"] tbody');
                const rows = [];
                if (tbody) {{
                    for (const row of tbody.querySelectorAll('tr')) {{
                        const category = row.querySelector('td.c1 div.categoryIcon span, .categoryIcon span')?.textContent?.trim() || null;
                        const status = row.querySelector('td.c2.rooms .svCabin .status, .svCabin .status')?.textContent?.trim() || '';
                        const radio = row.querySelector('input[name="rbCategorySelection"][data-columnindex="0"]')
                                   || row.querySelector('input[type="radio"]');
                        const c2Cells = Array.from(row.querySelectorAll('td.c2:not(.clearCell)')).map(td => td.textContent.trim());
                        const c3Cells = Array.from(row.querySelectorAll('td.c3:not(.clearCell)')).map(td => td.textContent.trim());
                        rows.push({{
                            category,
                            status,
                            radioValue: radio?.value || null,
                            radioChecked: Boolean(radio?.checked),
                            promo: row.querySelector('.promo, .currentPromo')?.textContent?.trim() || '',
                            rowText: row.innerText.trim(),
                            c2Cells,
                            c3Cells,
                        }});
                    }}
                }}
                const token = location.href.match(/execution=(e\\d+s\\d+)/)?.[1] || null;
                const selectionJSON = document.querySelector('input.selectionJSON, input[name*="selectionJSON"]')?.value || '';
                const c2Header = document.querySelector('th.columnSelection.c2 label');
                const c3Header = document.querySelector('th.columnSelection.c3 label');
                const c2Radio = document.querySelector('input[name="columnSelection"].c2');
                return {{
                    ok: true,
                    currentCategory: {json.dumps(current_category)},
                    executionToken: token,
                    selectionJSON,
                    rows,
                    dualRateColumns: Boolean(c2Header || c3Header),
                    c2Label: c2Header?.textContent?.trim() || null,
                    c3Label: c3Header?.textContent?.trim() || null,
                    activeColumn: (c2Radio ? (c2Radio.checked ? 'c2' : 'c3') : null),
                }};
            }})()
        """)
        return result

    async def _read_page_data(self, category: str | None) -> dict:
        """Read execution token, selection JSON, and radio value from page."""
        cat_js = f"'{category}'" if category else "null"
        result = await self.page.evaluate(f"""
            (async () => {{
                const m = location.href.match(/execution=(e\\d+s\\d+)/);
                const token = m ? m[1] : null;
                let radio = '1';
                const sel0 = document.querySelector('input.selectionJSON, input[name*="selectionJSON"]');
                const beforeJson = sel0?.value || '';
                const cat = {cat_js};
                const tbody = document.querySelector('#catAvailCategoryList tbody')
                           || document.querySelector('[id*="catAvail"] tbody');
                if (tbody && cat) {{
                    for (const row of tbody.querySelectorAll('tr')) {{
                        const icon = row.querySelector('td.c1 div.categoryIcon span, .categoryIcon span');
                        if (icon && icon.textContent.trim() === cat) {{
                            const r = row.querySelector('input[name="rbCategorySelection"][data-columnindex="0"]')
                                   || row.querySelector('input[type="radio"]');
                            if (r) {{
                                radio = r.value;
                                r.checked = true;
                                r.click();
                                r.dispatchEvent(new Event('change', {{ bubbles: true }}));
                                break;
                            }}
                        }}
                    }}
                }}
                const deadline = Date.now() + 2000;
                while (Date.now() < deadline) {{
                    await new Promise(res => setTimeout(res, 100));
                    const cur = document.querySelector('input.selectionJSON, input[name*="selectionJSON"]')?.value || '';
                    if (cur && cur !== beforeJson && cur !== '[]') break;
                }}
                await new Promise(res => setTimeout(res, 150));
                const selFinal = document.querySelector('input.selectionJSON, input[name*="selectionJSON"]');
                return {{ executionToken: token, selectionJSON: selFinal?.value || '[]', radioValue: radio }};
            }})()
        """)
        return result

    async def _read_top_prices(self) -> dict:
        """Read the two 'viewPriceQuoteLink' price figures shown at the top
        of the categories page — the reservation's current price
        (sb.summary.price.price) and the price for whichever category
        radio is currently selected (sb.summary.price.allocationPrice).
        These are rendered directly from the page's own Angular state, so
        they're a reliable "did the price actually change" check — cheaper
        and more trustworthy than the showRepriceModalCheck fetch, which
        returns a short, non-JSON body specifically when there's no real
        change (previously misdiagnosed downstream as an expired token).
        """
        result = await self.page.evaluate("""
            (() => {
                const parseAmt = (el) => {
                    if (!el) return null;
                    const n = parseFloat((el.textContent || '').replace(/[^0-9.\\-]/g, ''));
                    return isNaN(n) ? null : n;
                };
                const links = Array.from(document.querySelectorAll('a.viewPriceQuoteLink.fit'));
                const currentEl = links.find(el => (el.getAttribute('ng-show') || '').includes('sb.summary.price.price'));
                const allocEl = links.find(el => (el.getAttribute('ng-show') || '').includes('sb.summary.price.allocationPrice'));
                return { currentPrice: parseAmt(currentEl), allocationPrice: parseAmt(allocEl) };
            })()
        """)
        return result

    async def _confirm_candidate_total(self, category: str) -> float | None:
        """Get ESPRESSO's own REAL confirmed total for `category` — never
        an estimate. Runs the exact same allocate()+repriceModalCheck()
        sequence already trusted for OPTIMIZATION/TRAP (same safety
        boundary: never touches the actual "Continue with New Rate" commit
        button), then reads the confirmed total back via _read_top_prices()
        rather than parsing repriceModalCheck's JSON body.

        Confirmed live 2026-08-01 (booking 3000002, candidate J3):
        repriceModalCheck can return {"key": "skipRepriceModal"} — meaning
        this booking can't COMMIT a reprice into this category — while
        sb.summary.price.allocationPrice still updates to the real
        confirmed total regardless. Those are different questions ("can I
        confirm this" vs "what would it cost"), and only the second one is
        needed to know whether a category is a genuine upgrade. Verified
        against all 6 bookings from the original false-positive incident:
        every one now correctly shows a real cost INCREASE ($401-$5,459),
        matching manual verification that none of them were real upgrades.

        Returns None if no price was ever rendered (never treat missing
        data as a signal of savings).
        """
        page_data = await self._read_page_data(category)
        if not page_data.get("executionToken"):
            return None
        await self._execute_api_calls(
            page_data["executionToken"], page_data["selectionJSON"], page_data["radioValue"],
        )
        # Let Angular finish recomputing/rendering the allocation price
        # after the real allocate() response comes back.
        await asyncio.sleep(1.0)
        top_prices = await self._read_top_prices()
        return top_prices.get("allocationPrice")

    async def _execute_api_calls(self, token: str, selection_json: str, radio: str) -> dict:
        """Execute the allocate + reprice API calls inside the page context."""
        result = await self.page.evaluate(f"""
            (async () => {{
                try {{
                    const b1 = new URLSearchParams({{
                        'columnSelection': 'on',
                        'rbCategorySelection': '{radio}',
                        '_eventId': 'saveCategories',
                        'categorySingleViewFormModel.selectionJSON': {json.dumps(selection_json)}
                    }}).toString();
                    const r1 = await fetch(
                        '/espresso/protected/reservations.do?execution={token}&_eventId=allocate&ajaxSource=true',
                        {{ method:'POST', headers:{{ 'Content-Type':'application/x-www-form-urlencoded; charset=UTF-8', 'X-Requested-With':'XMLHttpRequest' }}, body:b1, credentials:'include' }}
                    );
                    if (!r1.ok) return {{ ok:false, error:'Allocate HTTP ' + r1.status }};
                    await new Promise(res => setTimeout(res, 300));
                    const r2 = await fetch(
                        '/espresso/protected/repriceModalController.do/showRepriceModalCheck?execution={token}',
                        {{ method:'POST', headers:{{ 'Content-Type':'application/x-www-form-urlencoded', 'X-Requested-With':'XMLHttpRequest', 'Accept':'application/json' }}, body:'execution={token}', credentials:'include' }}
                    );
                    if (!r2.ok) return {{ ok:false, error:'Reprice HTTP ' + r2.status }};
                    const text = await r2.text();
                    try {{ return {{ ok:true, data: JSON.parse(text), dataLength: text.length }}; }}
                    catch(e) {{ return {{ ok:false, error:'Not JSON: ' + text.substring(0, 200) }}; }}
                }} catch(e) {{ return {{ ok:false, error:e.message }}; }}
            }})()
        """)
        return result

    async def check_booking(self, booking_id: str, capture_market_data: bool = False) -> BookingResult:
        """
        Full ESPRESSO booking check flow.

        Steps: navigate → login check → search → read category →
        load categories → WLT check → execute API → calculate result.
        """
        price_category: str | None = None
        # ADDED 2026-08-13 (Phase 0 correctness audit): the real currency
        # code detected from the Reservation Summary page text (see
        # _read_payment_status/_CURRENCY_LABEL_RE), or None if no
        # recognizable label was found. Applied to whatever BookingResult
        # is ultimately returned, further down, regardless of which branch
        # produced it — never assumed "USD" when this stays None.
        detected_currency: str | None = None
        self.last_market_data = None

        async def _attempt():
            nonlocal price_category, detected_currency

            # Go through the portal home page first, the same path a human
            # takes right after login — deep-linking straight to
            # reservations.do skips whatever session/flow initialization
            # /home does, and appears to be what was causing the forced
            # logouts and desynced execution tokens seen during testing.
            logger.info("espresso.navigate_home", booking_id=booking_id)
            self.log_action("navigate", booking_id=booking_id, url=settings.espresso_home_url)
            await self.navigate(settings.espresso_home_url)
            if not await self._check_login():
                raise RuntimeError("Not logged in — please log into ESPRESSO first")

            logger.info("espresso.navigate", booking_id=booking_id)
            self.log_action("navigate", booking_id=booking_id, url=settings.espresso_base_url)
            await self.navigate(settings.espresso_base_url)
            if not await self._check_login():
                raise RuntimeError("Not logged in — please log into ESPRESSO first")

            # Early-warning structure check (once per session, not once
            # per booking — see check_structure_drift's docstring). Never
            # blocks the actual search below even if this itself fails to
            # find the element — that failure is informative on its own.
            await self.check_structure_drift("espresso_search_input", self._SEARCH_INPUT_SELECTOR)
            await self.check_structure_drift("espresso_search_button", self._SEARCH_BUTTON_SELECTOR)

            logger.info("espresso.search", booking_id=booking_id)
            self.log_action("search_booking", booking_id=booking_id)
            try:
                await self._search_booking(booking_id)
            except Exception as e:
                await self.dump_failure_snapshot(booking_id, "search_booking_failed", str(e))
                raise
            await self.dump_page_snapshot(booking_id, "after_search")

            price_category = await self._read_category()
            logger.info("espresso.category", booking_id=booking_id, category=price_category)
            self.log_action("read_category", booking_id=booking_id, category=price_category)

            # Paid-in-full early gate — runs before Categories is even
            # clicked, using the Reservation Summary page's own "Final
            # Payment Due (USD)" figure (see is_paid_in_full/
            # _read_payment_status). Catches this regardless of what the
            # reprice-modal API would have returned — a real booking
            # (3000040) was previously slipping through as a false
            # "$77 OPTIMIZATION" because its API response was a normal
            # length, so the old reactive-only paid-status check never ran.
            payment_status = await self._read_payment_status()
            detected_currency = payment_status.get("currency")
            self.log_action("payment_status", booking_id=booking_id, **payment_status)
            if is_paid_in_full(
                payment_status.get("final_payment_due"),
                payment_status.get("total_price") or 0.0,
            ):
                return {"_paidInFull": True, "oldTotal": payment_status.get("total_price") or 0.0}

            # Click categories and load the table
            self.log_action("click_categories", booking_id=booking_id)
            await self._click_categories()
            await self.dump_page_snapshot(booking_id, "categories_table")

            # Always captured now (not just when capture_market_data is on)
            # — find_free_upgrade() needs these rows for every booking, not
            # just ones being logged for analysis. capture_market_data still
            # controls whether this gets persisted to the market_data table.
            self.last_market_data = await self._capture_category_table(price_category)
            if capture_market_data:
                logger.info(
                    "espresso.market_data_captured",
                    booking_id=booking_id,
                    current_category=price_category,
                    rows_count=len(self.last_market_data.get("rows", [])),
                )

            # WLT check (AFTER categories table is loaded — fix from v6.3)
            if price_category and await self._check_wlt(price_category):
                return {"_wlt": True}

            page_data = await self._read_page_data(price_category)
            if not page_data.get("executionToken"):
                raise RuntimeError("No execution token in URL")

            logger.info("espresso.api_calls", booking_id=booking_id, token=page_data["executionToken"])
            self.log_action("execute_api_calls", booking_id=booking_id, token=page_data["executionToken"])
            api_result = await self._execute_api_calls(
                page_data["executionToken"],
                page_data["selectionJSON"],
                page_data["radioValue"],
            )

            # ESPRESSO's own API deliberately returns this shape — it is
            # not an error or an expired token, it's a clean "this booking
            # has a restriction that blocks repricing" (confirmed against
            # the portal's own "Booking Restriction: Changing price pgm
            # is not allowed" message). No point retrying — it won't change.
            if api_result.get("ok") and (api_result.get("data") or {}).get("key") == "skipRepriceModal":
                logger.info("espresso.skip_reprice", booking_id=booking_id)
                return {"_skipRepriceModal": True}

            short_response = (api_result.get("dataLength") or 0) < 300
            if not api_result.get("ok") or short_response:
                if short_response:
                    paid = await self._check_paid_status()
                    if paid and paid.get("isPaid"):
                        return {"_paidInFull": True, "oldTotal": paid.get("totalPrice", 0)}

                    # A short/non-JSON response from showRepriceModalCheck is
                    # what the portal returns when there's genuinely nothing
                    # to compare. Confirm that against the page's own
                    # displayed price — read only now, after the real
                    # allocate/reprice calls have actually run, never as a
                    # pre-emptive skip (an earlier version of this check ran
                    # before the API call and produced false "no change"
                    # verdicts, because the page hadn't updated yet at that
                    # point — masking real optimizations).
                    top_prices = await self._read_top_prices()
                    current_price = top_prices.get("currentPrice")
                    allocation_price = top_prices.get("allocationPrice")
                    if (
                        current_price is not None
                        and allocation_price is not None
                        and abs(current_price - allocation_price) < 0.01
                    ):
                        logger.info("espresso.no_price_change", booking_id=booking_id, price=current_price)
                        self.log_action("price_check", booking_id=booking_id, result="no_change", price=current_price)
                        return {"_noPriceChange": True, "price": current_price}

                if not api_result.get("ok"):
                    logger.warning("espresso.api_call_failed", booking_id=booking_id, error=api_result.get("error"))
                    raise RuntimeError(api_result.get("error", "API failed"))

                # Log + persist the actual short body instead of just its
                # length — "token expired" was a guess; this shows what
                # the portal is really saying so we can classify it properly.
                body = api_result.get("data")
                logger.warning(
                    "espresso.short_response",
                    booking_id=booking_id,
                    data_length=api_result.get("dataLength"),
                    body=body,
                )
                self.dump_raw(booking_id, {"short_response": True, "dataLength": api_result.get("dataLength"), "body": body})
                raise RuntimeError(f"API returned only {api_result.get('dataLength')} chars — body: {body}")

            self.dump_raw(booking_id, api_result.get("data"))
            return api_result

        api_result = await retry_async(
            _attempt,
            attempts=settings.scraper_retry_attempts,
            delay_s=settings.scraper_retry_delay_ms / 1000,
            label=f"ESPRESSO {booking_id}",
        )

        # Handle sentinel results
        if api_result.get("_wlt"):
            return make_wlt_result(booking_id, price_category, CruiseLine.ESPRESSO)
        if api_result.get("_paidInFull"):
            return make_paid_in_full_result(
                booking_id, price_category, CruiseLine.ESPRESSO, api_result.get("oldTotal", 0),
            )
        if api_result.get("_skipRepriceModal"):
            return make_skip_reprice_result(booking_id, price_category, CruiseLine.ESPRESSO)
        if api_result.get("_noPriceChange"):
            return make_no_price_change_result(
                booking_id, price_category, CruiseLine.ESPRESSO, api_result.get("price", 0),
            )

        result = calculate_espresso(api_result["data"], booking_id, price_category)

        # RE-ENABLED 2026-08-01 with a real fix — see core/calculator.py's
        # "ESPRESSO Free-Upgrade Detection" module docstring for the full
        # incident history (design #3 was confirmed wrong against real
        # data: 6 false positives from comparing a per-person table price
        # to a whole-booking total). find_upgrade_candidates() is a free,
        # unit-safe pre-filter only — it decides nothing. Every candidate
        # it returns still gets a real allocate()+repriceModalCheck() round
        # trip via _confirm_candidate_total(), and only a REAL confirmed
        # total that's actually <= old_total is ever surfaced. Verified
        # live against all 6 original false positives: every one now
        # correctly comes back as costing more, not less.
        if result.status == BookingStatus.NO_SAVING and self.last_market_data:
            candidates = find_upgrade_candidates(price_category, self.last_market_data.get("rows", []))
            best: dict | None = None
            for candidate in candidates:
                confirmed_total = await self._confirm_candidate_total(candidate["category"])
                logger.info(
                    "espresso.upgrade_candidate_confirmed",
                    booking_id=booking_id, category=candidate["category"], confirmed_total=confirmed_total,
                )
                if confirmed_total is None or confirmed_total > result.old_total:
                    continue
                if best is None or confirmed_total < best["price"]:
                    best = {"category": candidate["category"], "room_type": candidate["room_type"], "price": confirmed_total}
            if best is not None:
                result = make_upgrade_available_result(
                    booking_id, price_category, CruiseLine.ESPRESSO, result.old_total, best,
                )

        # Applied uniformly to every branch above (sentinel WLT/paid-in-full/
        # skip-reprice/no-price-change results, the main calculated result,
        # and the upgrade-available override) — "UNKNOWN" unless the page
        # text actually showed a recognizable currency label this run.
        result.currency = detected_currency or "UNKNOWN"

        # ADDED 2026-08-13 (Phase 0 correctness audit): _capture_category_table
        # already captures the c3 (alternate rate-program) column's raw cell
        # text for bookings that render one, but — per that function's own
        # docstring — never feeds it into any pricing decision, since no live
        # capture exists confirming what c3's cell format actually means or
        # how it compares to c2's. Deliberately NOT adding speculative price
        # comparison/selection logic here — there's no evidence to build it
        # on, and guessing wrong here is exactly the failure class the
        # free-upgrade-detection incident history in core/calculator.py
        # warns against. Instead: make the KNOWN ambiguity visible rather
        # than silently absent — a human reviewing this result now knows a
        # second, unevaluated rate-program column exists on this booking.
        result.note = _append_dual_rate_note(result.note, self.last_market_data)

        logger.info("espresso.result", booking_id=booking_id, status=result.status.value, net=result.net_saving)
        self.log_action("result", booking_id=booking_id, status=result.status.value, net_saving=result.net_saving)
        return result
